module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    colors: {
      "primary-soft-blue": "#8bacda",
      "primary-cyan": "#00fff7",
      "neutral-main-dark-blue": "#0d192b",
      "neutral-card-dark-blue": "#14253d",
      "neutral-line-dark-blue": "#2f415b",
      "neutral-light-gray": "hsl(0, 0%, 81%)",
      "neutral-light-grayish-blue": "hsl(210, 46%, 95%)",
      white: "#ffffff",
      "dark-grayish-blue": "hsl(217, 19%, 35%)",
      "dark-blackish-blue": "hsl(219, 29%, 14%)",
      "neutral-1": "#ffffff",
      "neutral-2": "hsl(0, 0%, 81%)",
      "neutral-3": "hsl(210, 46%, 95%)",
      "neutral-4": "hsl(217, 19%, 35%)",
      "neutral-5": "hsl(219, 29%, 14%)",
      violet: "hsl(263, 55%, 52%)",
    },
    screens: {
      xxs: "480px",
      xs: "640px",
      sm: "768px",
      md: "1024px",
      lg: "1280px",
      xl: "1440px",
    },
    fontFamily: {
      sans: ["Outfit", "sans-serif"],
    },
    extend: {
      backgroundImage: {
        "cover-image": "url(/stats-card/image-header-desktop.jpg)",
        quotation: "url('/testimonials-grid/quotation.svg')",
        sunnyside: "url('/sunnyside-agency/image-header.jpg')",
        "sunnyside-cherry": "url('/sunnyside-agency/image-graphic-design.jpg')",
        "sunnyside-orange": "url('/sunnyside-agency/image-photography.jpg')",
      },
      colors: {
        "primary-soft-blue": "#8bacda",
        "primary-cyan": "#00fff7",
        "neutral-main-dark-blue": "#0d192b",
        "neutral-card-dark-blue": "#14253d",
        "neutral-line-dark-blue": "#2f415b",
        white: "#ffffff",
        "main-bg": "hsl(233, 47%, 7%)",
        "card-bg": "hsl(244, 38%, 16%)",
        accent: "hsl(277, 64%, 61%)",
        "neutral-white": "hsl(0, 0%, 100%)",
        "neutral-white-main": "hsla(0, 0%, 100%, 0.75)",
        "neutral-white-stat": "hsl(0, 0%, 100%, 0.6)",
        "soft-red": "hsl(7, 99%, 70%)",
        yellow: "hsl(51, 100%, 49%)",
        "desat-cyan": "hsl(167, 40%, 24%)",
        "ver-dark-desat-cyan": "hsl(212, 27%, 19%)",
        "dark-blue": "hsl(198, 62%, 26%)",
        "moderate-cyan": "hsl(168, 34%, 41%)",
        "sunny-very-dark-grayish-blue": "hsl(213, 9%, 39%)",
        "sunny-dark-grayish-blue": "hsl(232, 10%, 55%)",
        "sunny-grayish-blue": "hsl(210, 4%, 67%)",
        "sunnyside-blue": "hsl(200, 100%, 62%)",
        "sunnyside-footer": "hsl(167, 44%, 70%)",
      },
      fontSize: {
        xxs: "10px",
      },
      fontFamily: {
        sans: ["Outfit", "sans-serif"],
      },
      spacing: {
        "vh-1": "10vh",
        "vh-2": "20vh",
        "vh-3": "30vh",
        "vh-4": "40vh",
        "vh-5": "50vh",
        "vh-6": "60vh",
        "vh-7": "70vh",
        "vh-8": "80vh",
        "vh-9": "90vh",
      },
      minWidth: {
        8: "32px",
        "1/2": "50%",
      },
      screens: {
        mobile: "375px",
        desktop: "1440px",
      },
    },
  },
  plugins: [],
};
